### ISSUE TITLE
Ability to query image by tag(s)

### ISSUE THREAD

**Issue by akopachov** [tusik/AnimeApi#7]
It would be nice to have the ability to query images that definitely include given tag(s). Like inversed `nin` param.

Proposed behavior:

Every call to `GET: https://pic.re/image?in=long_hair` returns an image that has the tag "long_hair".

**Comment by tusik** [comment]
good idea, I will complete it soon

**Comment by tusik** [comment]
Searching with tags is avaliable. When no matching images are found, an empty ImageDetail object will be returned.

**Comment by akopachov** [comment]
Thanks a lot. Today finished integrating pic.re into my own project - [SvelTab](https://github.com/akopachov/sveltab)

And having this feature available makes it so much easier and more flexible to tune the background.

Thanks again
